

import type { UserRole } from './types';

// =================================================================================
// PERMISSIONS CONFIGURATION
// =================================================================================
// This is where you can define which navigation items are visible to each user role.
//
// How to use:
// 1. For each role, list the IDs of the navigation items they should see.
// 2. The IDs correspond to the 'id' field in `src/lib/nav-items.ts`.
// 3. If a role should see a parent navigation item (like 'Sales'), you must also
//    list the IDs of the child items they should see (e.g., 'sales-lead').
// 4. The 'Admin' role automatically gets access to everything, so you don't need
//    to list its permissions here.
//
// Example:
// const permissions: Record<UserRole, string[]> = {
//   Customer: ['dashboard', 'shop'],
//   'Sales Agent': ['dashboard', 'sales', 'sales-lead', 'sales-offers'],
//   ...
// };
// =================================================================================

const permissions: Partial<Record<UserRole, string[]>> = {
  // --- Define your role permissions below ---
  Admin: [
    'command-center',
    'command-center-goals',
    'command-center-timeline',
    'command-center-leaderboard',
    'procurement-record-purchase', 
    'finance-gst',
    'finance-statutory-metrix',
    'finance-balance-sheet',
    'finance-profit-and-loss',
    'finance-trial-balance',
    'finance-transactions',
    'finance-chart-of-accounts',
    'sales',
    'sales-partners-management',
  ],
  'Partner': [
    'dashboard',
    'notifications',
    'shop',
    'my-orders',
    'wishlist',
    'my-products',
    'my-account',
    'referrals',
    'deals-offers',
    'parties',
    'my-task',
    'create-task',
    'create-post',
    'reimbursement',
    'sales',
    'sales-lead',
    'sales-quotation',
    'sales-orders',
    'sales-commission-report',
    'help',
    'profiles-settings',
  ],
  'CEO': [
    'command-center',
    'command-center-goals',
    'command-center-timeline',
    'command-center-leaderboard',
    'notifications',
    'my-account',
    'referrals',
    'deals-offers',
    'parties',
    'my-task',
    'create-task',
    'my-attendance',
    'reimbursement',
    'gate-keeper',
    'sales',
    'sales-lead',
    'sales-quotation',
    'sales-orders',
    'sales-partners-management',
    'production',
    'production-products',
    'production-categories',
    'production-bom',
    'production-work-orders',
    'production-task-matrix',
    'production-quality-control',
    'finance',
    'finance-chart-of-accounts',
    'finance-record-purchase',
    'finance-bank-cash',
    'finance-invoice',
    'finance-balance-sheet',
    'finance-profit-and-loss',
    'finance-trial-balance',
    'finance-gst',
    'finance-statutory-metrix',
    'finance-reimbursement-process',
    'finance-transactions',
    'finance-day-book',
    'procurement',
    'procurement-record-purchase',
    'procurement-requested',
    'procurement-analysis',
    'procurement-orders',
    'procurement-notes',
    'procurement-approval',
    'inventories-reports',
    'inventories-stocks',
    'inventories-inwards',
    'inventories-outwards',
    'inventories-reconciliation',
    'inventories-spares-request',
    'hr',
    'hr-vacancies',
    'hr-cvs',
    'hr-on-board',
    'hr-off-board',
    'hr-attendance',
    'hr-payroll',
    'hr-settings',
    'service-warranty',
    'service-warranty-warranty',
    'service-warranty-service',
    'company-settings',
    'company-settings-company',
    'company-settings-users',
    'company-settings-commission',
    'create-deals-offer',
    'help',
    'profiles-settings',
    'approvals',
    'hr-tracking',
    'create-post',
    'wishlist',
  ],
  'Customer': [
    'dashboard',
    'notifications',
    'shop',
    'my-orders',
    'my-products',
    'my-account',
    'referrals',
    'deals-offers',
    'help',
    'profiles-settings',
    'create-post',
    'wishlist',
],
  'Sales Manager': [
    'notifications',
    'my-account',
    'referrals',
    'deals-offers',
    'parties',
    'my-task',
    'create-task',
    'my-attendance',
    'reimbursement',
    'sales',
    'sales-lead',
    'sales-quotation',
    'sales-orders',
    'sales-partners-management',
    'service-warranty',
    'service-warranty-warranty',
    'service-warranty-service',
    'help',
    'profiles-settings',
    'approvals',
    'hr-tracking',
    'create-post',
    'company-settings',
    'company-settings-users',
    'create-deals-offer',
    'wishlist',
  ],
  'Production Manager': [
    'notifications',
    'my-account',
    'referrals',
    'deals-offers',
    'parties',
    'my-task',
    'create-task',
    'my-attendance',
    'reimbursement',
    'production',
    'production-products',
    'production-categories',
    'production-bom',
    'production-work-orders',
    'production-task-matrix',
    'production-quality-control',
    'procurement',
    'procurement-requested',
    'procurement-analysis',
    'procurement-orders',
    'procurement-notes',
    'procurement-approval',
    'service-warranty',
    'service-warranty-warranty',
    'service-warranty-service',
    'help',
    'profiles-settings',
    'approvals',
    'create-post',
    'wishlist',
  ],
  'Purchase Manager': [
    'notifications',
    'my-account',
    'referrals',
    'deals-offers',
    'parties',
    'my-task',
    'create-task',
    'my-attendance',
    'reimbursement',
    'procurement',
    'procurement-record-purchase',
    'procurement-requested',
    'procurement-analysis',
    'procurement-orders',
    'procurement-notes',
    'procurement-approval',
    'inventories-reports',
    'inventories-stocks',
    'inventories-inwards',
    'inventories-outwards',
    'inventories-reconciliation',
    'help',
    'profiles-settings',
    'approvals',
    'create-post',
    'finance',
    'finance-payments',
    'wishlist',
  ],
  'Service Manager': [
    'notifications',
    'my-account',
    'referrals',
    'deals-offers',
    'parties',
    'my-task',
    'create-task',
    'my-attendance',
    'reimbursement',
    'service-warranty',
    'service-warranty-warranty',
    'service-warranty-service',
    'help',
    'profiles-settings',
    'approvals',
    'create-post',
    'sales',
    'sales-lead',
    'sales-quotation',
    'sales-orders',
    'wishlist',
    'inventories-reports',
    'inventories-spares-request'
  ],
  'Accounts Manager': [
    'notifications',
    'my-account',
    'referrals',
    'deals-offers',
    'parties',
    'my-task',
    'create-task',
    'my-attendance',
    'reimbursement',
    'sales',
    'sales-lead',
    'sales-quotation',
    'sales-orders',
    'sales-partners-management',
    'production',
    'production-products',
    'production-categories',
    'production-bom',
    'production-work-orders',
    'production-task-matrix',
    'production-quality-control',
    'finance',
    'finance-chart-of-accounts',
    'finance-record-purchase',
    'finance-bank-cash',
    'finance-invoice',
    'finance-balance-sheet',
    'finance-profit-and-loss',
    'finance-trial-balance',
    'finance-gst',
    'finance-day-book',
    'finance-statutory-metrix',
    'finance-reimbursement-process',
    'finance-transactions',
    'procurement',
    'procurement-record-purchase',
    'procurement-requested',
    'procurement-analysis',
    'procurement-orders',
    'procurement-notes',
    'procurement-approval',
    'inventories-reports',
    'inventories-stocks',
    'inventories-inwards',
    'inventories-outwards',
    'inventories-reconciliation',
    'hr',
    'hr-vacancies',
    'hr-cvs',
    'hr-on-board',
    'hr-off-board',
    'hr-attendance',
    'hr-payroll',
    'hr-settings',
    'service-warranty',
    'service-warranty-warranty',
    'service-warranty-service',
    'company-settings',
    'company-settings-company',
    'company-settings-users',
    'company-settings-commission',
    'create-deals-offer',
    'help',
    'profiles-settings',
    'approvals',
    'create-post',
    'wishlist',
  ],
  'HR Manager': [
    'notifications',
    'my-account',
    'referrals',
    'deals-offers',
    'parties',
    'my-task',
    'create-task',
    'my-attendance',
    'reimbursement',
    'hr',
    'hr-vacancies',
    'hr-cvs',
    'hr-on-board',
    'hr-off-board',
    'hr-attendance',
    'hr-payroll',
    'hr-settings',
    'help',
    'profiles-settings',
    'approvals',
    'company-settings',
    'create-deals-offer',
    'hr-tracking',
    'create-post',
    'wishlist',
  ],
  'Gate Keeper': [
    'notifications',
    'my-account',
    'referrals',
    'deals-offers',
    'parties',
    'my-task',
    'create-task',
    'my-attendance',
    'reimbursement',
    'gate-keeper',
    'help',
    'profiles-settings',
    'create-post',
    'wishlist',
  ],
  'Inventory Manager': [
    'notifications',
    'my-account',
    'referrals',
    'deals-offers',
    'parties',
    'my-task',
    'create-task',
    'my-attendance',
    'reimbursement',
    'inventories-reports',
    'inventories-stocks',
    'inventories-inwards',
    'inventories-outwards',
    'inventories-reconciliation',
    'help',
    'profiles-settings',
    'approvals',
    'create-post',
    'wishlist',
    'inventories-spares-request'
  ],
  'Employee': [
    'notifications',
    'my-account',
    'referrals',
    'deals-offers',
    'my-task',
    'create-task',
    'my-attendance',
    'reimbursement',
    'help',
    'profiles-settings',
    'hr-tracking',
    'create-post',
    'wishlist',
  ],

  // --- End of role permissions definition ---
};

export function hasPermission(role: UserRole | null, navItemId: string): boolean {
  if (!role) {
    // For anonymous users, only allow access to a very limited set of public-safe items.
    const publicItems = ['shop'];
    return publicItems.includes(navItemId);
  }

  if (role === 'Admin') {
    return true;
  }
  
  if (role === 'CEO') {
    if (navItemId === 'switch-dashboard') return false;
    return permissions.CEO?.includes(navItemId) ?? false;
  }

  if (navItemId === 'switch-dashboard') {
    return role === 'Admin';
  }

  const rolePermissions = permissions[role] || [];
  
  if (rolePermissions.length > 0 && !rolePermissions.includes('dashboard') && navItemId === 'dashboard') {
    if (role !== 'Customer') {
        return true;
    }
  }

  return rolePermissions.includes(navItemId);
}
